<a href="https://colab.research.google.com/github/azadranjith/tensorflow/blob/main/tensorflow_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import tensorflow as tf

## handwritten digits prediction 
mnsit

In [57]:
mnist = tf.keras.datasets.mnist

In [58]:
#loading dataset

(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [9]:
x_train.shape


(60000, 28, 28)

In [154]:
#creating 3d tensor in tf
x = tf.constant([[[1.0,1.0,1.0,4],[3,3,3,2]],[[2,2,2,3],[4,3,4,4]]])
tf.math.reduce_mean(x,axis=1)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[2. , 2. , 2. , 3. ],
       [3. , 2.5, 3. , 3.5]], dtype=float32)>

In [55]:
import numpy as np

y=np.asarray(x_train[0])
y.shape

(28, 28)

In [72]:
x_test[0].shape

(28, 28)

In [11]:
import cv2 as cv

In [13]:
from google.colab.patches import cv2_imshow #imshow will not work in colab thats why we import this

In [71]:

cv2_imshow(x_test[0])

In [74]:
#to find the mean in tf
x=tf.math.reduce_mean(x_test,axis=0,keepdims=True)

In [92]:
#just showed ideal number (mean of digits in dataset)
cv2_imshow(np.asarray(x[0]))

In [93]:
#converting all the values between one and zero
x_train = x_train/255.0
x_test = x_test/255.0

In [95]:
a = tf.constant([[1,2,3]])
b = tf.constant([[0,500,0]])

In [100]:
print(a + b,'\n',a * b,'\n')

tf.Tensor([[  1 502   3]], shape=(1, 3), dtype=int32) 
 tf.Tensor([[   0 1000    0]], shape=(1, 3), dtype=int32) 



In [103]:
a.shape

TensorShape([1, 3])

In [102]:
b.shape

TensorShape([1, 3])

In [155]:
tf.transpose(b)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[  0],
       [500],
       [  0]], dtype=int32)>

In [110]:
tf.transpose(b) @ a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[   0,    0,    0],
       [ 500, 1000, 1500],
       [   0,    0,    0]], dtype=int32)>

## building  a sequential model

In [244]:
model = tf.keras.Sequential(name = 'my_first_ser')
model.add
model.add(tf.keras.layers.Dense(128,activation = 'relu',name = 'layer1'))
                              #(out_shape)
model.add(tf.keras.layers.Dense(56,activation = 'relu', name = 'layer2'))
model.add(tf.keras.layers.Dense(20,activation='softmax'))

In [245]:
z = x_train[:1]
z=tf.constant(z.reshape(1,784))

In [246]:
x = tf.ones((1,784))
y = model(z).numpy()
# model.weights
y

array([[0.08112711, 0.05292052, 0.07525147, 0.06853732, 0.06682558,
        0.02349278, 0.03097521, 0.09060245, 0.02700738, 0.02809855,
        0.033902  , 0.08729573, 0.02819971, 0.05425013, 0.06454265,
        0.0254952 , 0.06013119, 0.01760472, 0.05216704, 0.03157329]],
      dtype=float32)

In [171]:

#loss function 

loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [247]:
loss(y_train[:1],y)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0225003>

### before start training configure and compile the model
by setting loss,optimizer,metrics

In [250]:
model.compile(optimizer='sgd',
              loss=loss,
              metrics=['accuracy'])

In [251]:
X_TRAIN = x_train.reshape(-1,784)
X_TRAIN=tf.constant(X_TRAIN)

In [252]:
model.fit(X_TRAIN,y_train,epochs=5)

Epoch 1/5


/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


1875/1875 [==============================] - 5s 2ms/step - loss: 0.6612 - accuracy: 0.8296
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2916 - accuracy: 0.9163
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2379 - accuracy: 0.9320
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2034 - accuracy: 0.9419
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1785 - accuracy: 0.9489


In [253]:
x_t = tf.constant(x_test.reshape(-1,784))

In [254]:
model.evaluate(x_t,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.1632 - accuracy: 0.9528


[0.16322599351406097, 0.9527999758720398]

In [261]:
y_test[118]

9

In [263]:
o=np.array(x_t[118]).reshape(-1,784)

In [264]:
model(o)

<tf.Tensor: shape=(1, 20), dtype=float32, numpy=
array([[6.1132334e-04, 5.4372169e-05, 9.9814159e-04, 1.3227296e-03,
        7.8812882e-02, 1.5340385e-03, 3.8104059e-04, 1.7930297e-02,
        5.0565102e-03, 8.9306229e-01, 1.1738964e-05, 4.7345213e-05,
        4.4133812e-06, 2.9849149e-05, 3.3754684e-05, 1.4440576e-05,
        2.9240648e-05, 5.8757092e-07, 8.4005624e-06, 5.6473124e-05]],
      dtype=float32)>