<a href="https://colab.research.google.com/github/azadranjith/tensorflow/blob/main/tensorflow_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [266]:
import tensorflow as tf

## handwritten digits prediction 
mnsit

In [267]:
mnist = tf.keras.datasets.mnist

In [268]:
#loading dataset

(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [269]:
x_train.shape


(60000, 28, 28)

In [270]:
import numpy as np

In [271]:
x_test[0].shape

(28, 28)

In [273]:
import cv2 as cv
#openCV library to show tensor as images

In [274]:
from google.colab.patches import cv2_imshow #imshow will not work in colab thats why we import this

In [275]:
cv2_imshow(x_test[0])

In [276]:
#converting all the values between one and zero
x_train = x_train/255.0
x_test = x_test/255.0

## building  a sequential model

In [291]:
model = tf.keras.Sequential(name = 'my_first_ser')
model.add
model.add(tf.keras.layers.Dense(128,activation = 'relu',name = 'layer1'))
                              #(128 is the number of nueoron)
model.add(tf.keras.layers.Dense(56,activation = 'relu', name = 'layer2'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))

In [292]:
type(x_train)

numpy.ndarray

In [293]:

z = x_train[:1]
z=tf.constant(z.reshape(1,784))#converting numpy array to tensor and reshaping it as a one d tensor
type(z)

tensorflow.python.framework.ops.EagerTensor

In [294]:
#testing by inputing a data to model
y = model(z).numpy()
y

array([[0.11442962, 0.09205119, 0.10070038, 0.12873718, 0.1104724 ,
        0.0573072 , 0.05744855, 0.12431764, 0.09532923, 0.1192067 ]],
      dtype=float32)

In [295]:
#loss function 
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [296]:
loss(y_train[:1],y)

<tf.Tensor: shape=(), dtype=float32, numpy=2.3455672>

### before start training configure and compile the model
by setting loss,optimizer,metrics

In [297]:
model.compile(optimizer='sgd',
              loss=loss,
              metrics=['accuracy'])

In [298]:
X_TRAIN = x_train.reshape(-1,784)
X_TRAIN=tf.constant(X_TRAIN)
#reshaping and transforming to tensor

In [299]:
#training for 5 epoches
model.fit(X_TRAIN,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.6253 - accuracy: 0.8332
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2974 - accuracy: 0.9135
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2454 - accuracy: 0.9289
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2116 - accuracy: 0.9390
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1863 - accuracy: 0.9463


In [300]:
x_t = tf.constant(x_test.reshape(-1,784))

In [301]:
#testing accuracy
model.evaluate(x_t,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.1770 - accuracy: 0.9491


[0.1769995540380478, 0.9491000175476074]

In [302]:
y_test[118]

9

In [303]:
o=np.array(x_t[118]).reshape(-1,784)

In [304]:
model(o)

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[3.4222635e-04, 1.5906922e-05, 4.8815599e-04, 4.4622051e-04,
        5.1271580e-02, 7.0065900e-04, 1.0233389e-04, 1.6179271e-02,
        2.9112303e-03, 9.2754239e-01]], dtype=float32)>